[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_universal_nft = "UnivNFTSoL1111111111111111111111111111111111"

[programs.devnet]
solana_universal_nft = "UnivNFTSoL1111111111111111111111111111111111"

[programs.testnet]
solana_universal_nft = "UnivNFTSoL1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "anchor run initialize-program"